/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaemtrie;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author bv110309
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        
        initComponents();
        
        listResultado.setModel( new DefaultListModel<String>() );
        
        textPaneTexto.setText( "" );
        adicionarTextoFormatado(
            "by sea sells she shells shore the by by shore she she sea ball pen chair",
            Color.BLACK, false, false
        );
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTexto = new javax.swing.JScrollPane();
        textPaneTexto = new javax.swing.JTextPane();
        painelPesquisa = new javax.swing.JPanel();
        lblBuscarPor = new javax.swing.JLabel();
        txtBuscarPor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollPaneResultado = new javax.swing.JScrollPane();
        listResultado = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em Trie");

        scrollPaneTexto.setViewportView(textPaneTexto);

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        lblBuscarPor.setText("Buscar por:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        listResultado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneResultado.setViewportView(listResultado);

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneResultado)
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarPor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesquisaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPor)
                    .addComponent(txtBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneTexto))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        // como obter o conteúdo de uma caixa de texto:
        // getText(), retorna o conteúdo do JTextField como String
        // trim(), remove espaços nas extremidades, retornando uma nova String
        String valor = txtBuscarPor.getText().trim();
        System.out.println( valor );
        
        // cria um item (como String) de exemplo
        String itemLista = String.format( 
            "%s: linha %d, coluna %d", 
            valor,
            1, 
            10
        );
        
        // obtém o modelo da lista, limpa e adiciona um item
        DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
        model.clear();
        model.addElement( itemLista );
        
        // adiciona texto formatado ao JTextPane
        adicionarTextoFormatado( valor, Color.BLUE, true, true );
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void adicionarTextoFormatado( String texto, Color cor, boolean italico, boolean negrito ) {
        
        try {
            
            SimpleAttributeSet as = new SimpleAttributeSet();
            StyleConstants.setForeground( as, cor );
            StyleConstants.setBold( as, negrito );
            StyleConstants.setItalic( as, italico );
            
            textPaneTexto.getDocument().insertString( textPaneTexto.getDocument().getLength(), texto, as );
            
        } catch ( BadLocationException exc ) {
            exc.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new JanelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JList<String> listResultado;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JScrollPane scrollPaneResultado;
    private javax.swing.JScrollPane scrollPaneTexto;
    private javax.swing.JTextPane textPaneTexto;
    private javax.swing.JTextField txtBuscarPor;
    // End of variables declaration//GEN-END:variables
}
