package buscaemtrie;

import aesd.ds.implementations.nonlinear.symtable.Trie;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

public class JanelaPrincipal extends javax.swing.JFrame {

    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {

        initComponents();

        listResultado.setModel(new DefaultListModel<String>());

        textPaneTexto.setText("");
        adicionarTextoFormatado(
                "by sea sells she shells shore the by by shore she she sea ball pen chair",
                Color.BLACK, false, false
        );

        btnBuscar.setBackground(new Color(40, 20, 200, 120));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTexto = new javax.swing.JScrollPane();
        textPaneTexto = new javax.swing.JTextPane();
        painelPesquisa = new javax.swing.JPanel();
        lblBuscarPor = new javax.swing.JLabel();
        txtBuscarPor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollPaneResultado = new javax.swing.JScrollPane();
        listResultado = new javax.swing.JList<>();
        paneCorMarcador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em Trie");

        scrollPaneTexto.setViewportView(textPaneTexto);

        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        lblBuscarPor.setText("Buscar por:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        listResultado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneResultado.setViewportView(listResultado);

        paneCorMarcador.setBackground(new java.awt.Color(255, 255, 0));
        paneCorMarcador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneCorMarcador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneCorMarcadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneCorMarcadorLayout = new javax.swing.GroupLayout(paneCorMarcador);
        paneCorMarcador.setLayout(paneCorMarcadorLayout);
        paneCorMarcadorLayout.setHorizontalGroup(
            paneCorMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        paneCorMarcadorLayout.setVerticalGroup(
            paneCorMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelPesquisaLayout = new javax.swing.GroupLayout(painelPesquisa);
        painelPesquisa.setLayout(painelPesquisaLayout);
        painelPesquisaLayout.setHorizontalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneResultado)
                    .addGroup(painelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPesquisaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(paneCorMarcador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(txtBuscarPor))))
                .addContainerGap())
        );
        painelPesquisaLayout.setVerticalGroup(
            painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPor)
                    .addComponent(txtBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneCorMarcador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneResultado)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                    .addComponent(painelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        SwingUtilities.invokeLater(() -> {

            new Thread(() -> {

                Trie<List<Posicao>> trie = new Trie<>();

                String valor = txtBuscarPor.getText().trim();
                String textoCompleto = textPaneTexto.getText();
                String[] textoDividido = textoCompleto.split("\\s+");

                int offsetAtual = 0;

                for (int i = 0; i < textoDividido.length; i++) {

                    String palavra = textoDividido[i];

                    int offset = textoCompleto.indexOf(palavra, offsetAtual);

                    List<Posicao> posicoes = trie.get(palavra);
                    if (posicoes == null) {
                        posicoes = new ArrayList<>();
                    }

                    posicoes.add(getPosicao(offset));

                    trie.put(palavra, posicoes);

                    offsetAtual = offset + palavra.length();

                }

                List<Posicao> resultado = trie.get(valor);

                // obtém o modelo da lista, limpa e adiciona um item
                DefaultListModel<String> model = (DefaultListModel<String>) listResultado.getModel();
                model.clear();

                grifar(valor, resultado);

                // cria os itens da lista 
                for (Posicao p : resultado) {
                    String itemLista = String.format(
                            "linha %d, coluna %d",
                            p.linha,
                            p.coluna
                    );
                    model.addElement(itemLista);
                }

            }).start();
        });


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void paneCorMarcadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCorMarcadorMouseClicked

        Color c = JColorChooser.showDialog(this, "Cor do Marcador", paneCorMarcador.getBackground());

        if (c != null) {
            paneCorMarcador.setBackground(c);
        }

    }//GEN-LAST:event_paneCorMarcadorMouseClicked

    private Posicao getPosicao(int offset) {

        Document documento = textPaneTexto.getDocument();
        Element raiz = documento.getDefaultRootElement();

        int linha = raiz.getElementIndex(offset);
        Element linhaElemento = raiz.getElement(linha);
        int coluna = offset - linhaElemento.getStartOffset();

        return new Posicao(linha + 1, coluna + 1);

    }

    private void grifar(String palavra, List<Posicao> posicoes) {

        Highlighter h = textPaneTexto.getHighlighter();
        h.removeAllHighlights();

        Highlighter.HighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(paneCorMarcador.getBackground());

        try {
            String textoCompleto = textPaneTexto.getText();
            int offsetAtual = 0;

            for (Posicao p : posicoes) {
                int inicio = textoCompleto.indexOf(palavra, offsetAtual);
                int fim = inicio + palavra.length();

                h.addHighlight(inicio, fim, painter);

                offsetAtual = fim;
            }
        } catch (BadLocationException exc) {
            exc.printStackTrace();
        }
    }

    private void adicionarTextoFormatado(String texto, Color cor, boolean italico, boolean negrito) {

        try {

            SimpleAttributeSet as = new SimpleAttributeSet();
            StyleConstants.setForeground(as, cor);
            StyleConstants.setBold(as, negrito);
            StyleConstants.setItalic(as, italico);

            textPaneTexto.getDocument().insertString(textPaneTexto.getDocument().getLength(), texto, as);

        } catch (BadLocationException exc) {
            exc.printStackTrace();
        }

    }

    private record Posicao(int linha, int coluna) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(() -> new JanelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JList<String> listResultado;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JPanel paneCorMarcador;
    private javax.swing.JScrollPane scrollPaneResultado;
    private javax.swing.JScrollPane scrollPaneTexto;
    private javax.swing.JTextPane textPaneTexto;
    private javax.swing.JTextField txtBuscarPor;
    // End of variables declaration//GEN-END:variables
}
